language: go
go:
  - "1.13.x"
  - "1.14.x"
  - "tip"

os:
  - linux

env:
  - GO111MODULE=on

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic -tags "long_test"

after_success:
  - bash <(curl -s https://codecov.io/bash)

