name: Create a tag

on:
  workflow_dispatch:
    inputs:
      ver:
        description: 'Tag name'
        required: true

jobs:
  release_tagging:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup git
      run: git config user.name "GitHub Actions Bot" && git config user.email "<>"

    - name: Tag commit
      run: git tag ${{ github.event.inputs.ver }}

    - name: Push tag
      run: git push --tags
